# Generated by Django 3.1.12 on 2025-06-20 04:59

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAcopio',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_residuo', djongo.models.fields.JSONField()),
                ('entidad', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('sitio_web', models.URLField(blank=True, max_length=500, null=True)),
                ('coordenadas', djongo.models.fields.EmbeddedField(model_container=api.models.Coordenadas)),
            ],
        ),
        migrations.CreateModel(
            name='MercadoOrganico',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('productos_destacados', djongo.models.fields.JSONField()),
                ('direccion', models.TextField()),
                ('horario', models.CharField(max_length=255)),
                ('coordenadas', djongo.models.fields.EmbeddedField(model_container=api.models.Coordenadas)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoRecargaElectrico',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('operador', models.CharField(max_length=255)),
                ('tipo_conector', djongo.models.fields.JSONField()),
                ('potencia_kw', models.FloatField()),
                ('direccion', models.TextField()),
                ('costo', models.CharField(max_length=255)),
                ('coordenadas', djongo.models.fields.EmbeddedField(model_container=api.models.Coordenadas)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoReciclaje',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_material', djongo.models.fields.JSONField()),
                ('direccion', models.TextField()),
                ('horario', models.CharField(max_length=255)),
                ('coordenadas', djongo.models.fields.EmbeddedField(model_container=api.models.Coordenadas)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hash_contrasena', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField()),
                ('puntos_favoritos', djongo.models.fields.ArrayField(model_container=api.models.PuntoFavorito)),
            ],
        ),
    ]
